In [2]:
# Example 2: Two layer neural network
# 2.1 Loading the reuired libraries
import tensorflow as tf
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plt

In [3]:
!rm -rf /tmp/mylogs 

'rm'은(는) 내부 또는 외부 명령, 실행할 수 있는 프로그램, 또는
배치 파일이 아닙니다.


In [4]:
# 2.2 Defining the Batch size, input dimension, hidden dimension and number of classes
N,D,H,C=64,1000,100,10

In [5]:
# 2.3 Defining the feedforward and loss function
def forward(x):
    a=tf.matmul(x,w1)
    a_relu=tf.nn.relu(a)
    scores=tf.matmul(a_relu,w2)
    return scores

def loss_fn(scores, y):
    probs= tf.nn.softmax(scores)
    loss= -tf.reduce_sum(y*tf.math.log(probs))
    return loss    


In [6]:
# 2.4 Simulating data matrices
xx=np.random.randn(N,D).astype(np.float32)
yy=np.zeros((N,C)).astype(np.float32)
yy[np.arange(N),np.random.randint(C,size=N)]=1
yy
xx
print(xx)
print(yy)

[[-0.30620092  0.6121021  -0.51349986 ...  0.91350806  0.01957748
  -0.10493634]
 [-0.05322716  0.21577805 -1.2289063  ...  0.24276444 -0.735463
   0.5966788 ]
 [-0.35886624 -0.931692   -0.7319115  ... -0.7755981   1.6776718
   1.1191316 ]
 ...
 [-2.1523843  -0.9705806   0.2650808  ... -1.3968186  -0.21647528
  -1.4177538 ]
 [ 1.0320874  -1.1789439  -0.49706334 ...  0.6995366  -0.9769039
   1.4032394 ]
 [ 0.32088438  1.8158057   0.68652695 ... -0.34562874  1.198389
  -1.3757789 ]]
[[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0.

In [7]:
# 2.5 Defining the Variables; Weight matrices w1 and w2
w1=tf.Variable(1e-3*np.random.randn(D,H).astype(np.float32),name="w1")
w2=tf.Variable(1e-3*np.random.randn(H,C).astype(np.float32),name="w2")

In [8]:
# 2.7 Perform training 
learning_rate=1e-2
optimizer=tf.keras.optimizers.Adam(learning_rate)

def train_step(x, y):
    with tf.GradientTape() as tape:
        scores = forward(x)
        loss = loss_fn(scores, y) #softmax #classification 
    gradients = tape.gradient(loss, [w1, w2])
    optimizer.apply_gradients(zip(gradients, [w1, w2]))
    return loss, w1, w2
    


In [9]:
# 2.8 Creating logs for Tensorboard
summary_writer = tf.summary.create_file_writer('/tmp/mylogs')
loss_list = []

for step in range(10): 
    loss, w1, w2 = train_step(xx, yy)
    loss_list.append(loss.numpy())
    
    with summary_writer.as_default():
        tf.summary.scalar('loss_summary', loss, step=step)
        tf.summary.histogram('w1_hist', w1, step=step)
        tf.summary.histogram('w2_hist', w2, step=step)


In [10]:
# 2.9 Check loss 
loss_list #점점 작아짐

[147.36502,
 138.74811,
 93.25854,
 44.156128,
 15.69539,
 4.483054,
 0.8133465,
 0.079950586,
 0.0056687943,
 0.00035561563]